#ifndef __TEXT_TYPES_H
#define __TEXT_TYPES_H

#include <stdint.h>

namespace godot {

namespace framework {

#define GUI_TEXT_ENUM(X) \
    X(LEVEL_GUI_MAIN_START_CALIBRATION_BOTTON) \
    X(LEVEL_GUI_MAIN_START_TEST_BOTTON) \
    X(LEVEL_GUI_MAIN_START_DEMO_BOTTON) \
    X(LEVEL_GUI_MAIN_OPTION_BOTTON) \
    X(LEVEL_GUI_MAIN_QUIT_BOTTON) \
\
    X(LEVEL_GUI_CALIBRATION_GYRO_DATA_LABEL) \
    X(LEVEL_GUI_CALIBRATION_ACCELEROMETER_DATA_LABEL) \
    X(LEVEL_GUI_CALIBRATION_MAGNETOMETER_DATA_LABEL) \
    X(LEVEL_GUI_CALIBRATION_PROGRESS_LABEL) \
\
    X(LEVEL_GUI_FUSION_QUATERNION_LABEL) \
\
    X(FLOAT_GUI_OPTION_TITLE_LABEL) \
    X(FLOAT_GUI_OPTION_LEVEL_TAB_TITLE) \
    X(FLOAT_GUI_OPTION_DISPLAY_TAB_TITLE) \
    X(FLOAT_GUI_OPTION_LANGUAGE_TAB_TITLE) \
    X(FLOAT_GUI_OPTION_WINDOW_MODE_OPTION_BUTTON_LABEL) \
    X(FLOAT_GUI_OPTION_WINDOW_MODE_OPTION_BUTTON_ITEM_WINDOWED) \
    X(FLOAT_GUI_OPTION_WINDOW_MODE_OPTION_BUTTON_ITEM_WINDOWED_FULLSCREEN) \
    X(FLOAT_GUI_OPTION_WINDOW_MODE_OPTION_BUTTON_ITEM_EXCLUSIVE_FULLSCREEN) \
    X(FLOAT_GUI_OPTION_LANGUAGE_OPTION_BUTTON_LABEL) \
    X(FLOAT_GUI_OPTION_CLOSE_BUTTON)


#define _ENUM_BUILD(name) name,
enum class EGuiText : int32_t { GUI_TEXT_ENUM(_ENUM_BUILD) };
#undef _ENUM_BUILD

} //namespace framework

} // namespace godot

#endif // __TEXT_TYPES_H
